export const TRACK_DEFINE = {
  // LANDING PAGE
  CLICK_BUTTON_TRY_FOR_FREE: 'CLICK_BUTTON_TRY_FOR_FREE',
  CLICK_BUTTON_START_JAMMING: 'CLICK_BUTTON_START_JAMMING',
  
  // LOGIN
  CLICK_BUTTON_CONTINUE_LOGIN: 'CLICK_BUTTON_CONTINUE_LOGIN',
  CLICK_BUTTON_LOGIN: 'CLICK_BUTTON_LOGIN',
  CLICK_BUTTON_RESEND_CODE: 'CLICK_BUTTON_RESEND_CODE',
  TYPE_INPUT_EMAIL: 'TYPE_INPUT_EMAIL',
  TYPE_INPUT_CODE: 'TYPE_INPUT_CODE',
  API_LOGIN_OTP_SUCCESS: 'API_LOGIN_OTP_SUCCESS',
  API_LOGIN_OTP_FAIL: 'API_LOGIN_OTP_FAIL',
  API_RESEND_OTP: 'API_RESEND_OTP',

  // MIC/SHARE SCREEN
  CLICK_BUTTON_MIC: 'CLICK_BUTTON_MIC',
  CLICK_BUTTON_SHARE_SCREEN: 'CLICK_BUTTON_SHARE_SCREEN',
  CLICK_BUTTON_SHARE_SCREEN_FULLSCREEN: 'CLICK_BUTTON_SHARE_SCREEN_FULLSCREEN',
  CLICK_BUTTON_SHARE_SCREEN_MIC: 'CLICK_BUTTON_SHARE_SCREEN_MIC',

  // JOIN/LEAVE
  CLICK_BUTTON_JOIN: 'CLICK_BUTTON_JOIN',
  CLICK_BUTTON_LEAVE: 'CLICK_BUTTON_LEAVE',

  // INVITE
  CLICK_BUTTON_INVITE_FROM_LISTROOM: 'CLICK_BUTTON_INVITE_FROM_LISTROOM',
  CLICK_BUTTON_INVITE_FROM_MENU: 'CLICK_BUTTON_INVITE_FROM_MENU',
  CLICK_BUTTON_INVITE_FROM_EMPTY_LISTROOM: 'CLICK_BUTTON_INVITE_FROM_EMPTY_LISTROOM',
  CLICK_BUTTON_INVITE_REMOVE_EMAIL: 'CLICK_BUTTON_INVITE_REMOVE_EMAIL',
  CLICK_BUTTON_INVITE_SEND: 'CLICK_BUTTON_INVITE_SEND',

  // SEARCH

  // FEEDBACK
  CLICK_BUTTON_FEEDBACK_FROM_MENU: 'CLICK_BUTTON_FEEDBACK_FROM_MENU',
  CLICK_BUTTON_FEEDBACK_SEND: 'CLICK_BUTTON_FEEDBACK_SEND',

  // LOGOUT
  CLICK_BUTTON_LOGOUT_FROM_MENU: 'CLICK_BUTTON_LOGOUT_FROM_MENU',

  // MENU
  CLICK_BUTTON_HAMBURGER_MENU: 'CLICK_BUTTON_HAMBURGER_MENU',
};

export const ACTION_PARAMS = {
  PRESS_ENTER: { key: 'action', value: 'PRESS_ENTER' },
  AUTO: { key: 'action', value: 'AUTO' }, // means that this action happens automatically, not from user action
  TURN_ON: { key: 'action', value: 'TURN_ON' },
  TURN_OFF: { key: 'action', value: 'TURN_OFF' },
  CLOSE: { key: 'action', value: 'CLOSE' },
  OPEN: { key: 'action', value: 'OPEN' },
}

export const STATUS_PARAMS = {
  SUCCESS: { key: 'status', value: 'SUCCESS' },
  FAIL: { key: 'status', value: 'FAIL' },
}

export const PAGE_NAMES = {
  LANDING_PAGE: 'LANDING_PAGE',
  HOME: 'HOME',
  LOGIN: 'LOGIN'
}